// wird wohl nicht mehr benötigt
function createtabconvert()
{
data=
[
    "fcard|fieldname|fielddescription|_roadnumber|roadnumber|_roadname|roadname|_era0|era0|_era1|era1|_era3|era2|eratext|_uic|uic|_comment|comment|_brake|brake|_speed|speed|_axleload|axleload|_wheelarrangement|wheelarrangement|_weight|weight|seats1|seats2|_lob|lob|_axlespacing|axlespacing|_cargoload|cargoload|_loadinglength|loadinglength|_loadingarea|loadingarea|_loadingvolume|loadingvolume|_loadnotes|loadnotes|rivpic|riv|line1|line2|line3|circulationpic|_homestation|homestation|_homedepot|homedepot|_heater|heater|_power|power|_notes|notes|_quantity|quantity|_useperiod|useperiod|_wagoncarriertruck|wagoncarriertruck|_modellabel|modellabel|_modelfeatures|modelfeatures|_owner|owner|_springbuffer|springbuffer|_coupler|coupler|_couplerhead|couplerhead|_wheelset|wheelset|_manufacturer|manufacturer|_modellob|modellob|_modelweight|modelweight|_wagonsign|wagonsign|_maintenance|maintenance|handlebars|signalholder|aged|nemshaft|kkkinematics|_wheelsetmanufacturer|wheelsetmanufacturer|innerdimension|flangeheight|_prototype|prototype|_mass|mass|_storagelocation|storagelocation|_drivelevels|drivelevels|dummy|_dccaddress|dccaddress|_protocol|protocol|light|analog|_roadpic|roadpic|_wagonpic|wagonpic|F0|F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12",
    "de-DE||||Nummer||Verwaltung||0. Epoche ||Epoche||2. Epoche|Gattungsbezeichnung||UIC||Beschreibung||Bremse||Geschwindigkeit||Achslast||Achsfolge||Gesamtgewicht|Sitzplätze 1|Sitzplätze 2||LÜP||Achsstand||Nutzlast||Ladelänge||Ladefläche||Ladevolumen||Ladehinweise|RIV|RIV|Linie1|Linie2|Linie3|Umlauf||HeimatBahnhof||HeimatBW||Heizung||Leistung||SonstigeHinweise||Stückzahl||Einsatzzeit||Rollbockfähig||Modellbeschriftung||Modellmerkmale||Eigentümer||Federpuffer||Kupplung||Kupplungskopf||Radsatznorm||Hersteller||ModellLÜP||Modellgewicht||Merkmal Wagenboden||Revision|Griffstangen|Signalhalter|Gealtert|NEMSchacht|KKKinematik||Radsatzhersteller|Innenmaß|Spurkranzhöhe||Vorbild||Masse||Ablageort||Fahrstufen|leer||Decoderaddresse||DCC Protokoll|Licht|Decoder analog||||Fahrzeugbild|F0|F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12",
    "en-US||||roadnumber||roadname||0. Era||Era||2. Era|Era ||uic||comment||brake||speed||axleload||wheelarrangement||weight|seats1|seats2||Lengthoverbuffer||axlespacing||cargoload||loadinglength||loadingarea||loadingvolume||loadnotes|rivpic|riv|line1|line2|line3|circulationpic||homestation||homedepot||heater||power||notes||quantity||useperiod||wagoncarriertruck ||modellabel||modelfeatures||owner||springbuffer||coupler||couplerhead||wheelset||Manufacturer||modellob||modelweight||wagonsign||maintenance|handlebars|signalholder|aged|nemshaft|kkkinematics||wheelsetManufacturer|innerdimension|flangeheight||prototype||mass||storagelocation||drivelevels|dummy||dccaddress||protocol|light|analog||||wagonpic|F0|F1|F2|F3|F4|F5|F6|F7|F8|F9|F10|F11|F12",
    "xwaca||||NR||Verwaltung||GBZII||GBZIII||GBZIV|||UIC||Beschreibung||Bremse||Geschwindigkeit||Achslast||Achsfolge||Gesamtgewicht|Sitzplätze 1|Sitzplätze 2||LÜP||Achsstand||Nutzlast||Ladelänge||Ladefläche||Ladevolumen||Ladehinweise||RIV|Linie1|Linie2|Linie3|Umlauf||HeimatBahnhof||HeimatBW||Heizung||Leistung||SonstigeHinweise||Stückzahl||Einsatzzeit||Rollbockfähig||Modellbeschriftung||Modellmerkmale||Eigentümer||Federpuffer||Kupplung||Kupplungskopf||Radsätze||Hersteller||ModellLÜP||Modellgewicht||Merkmal Wagenboden||Revision|Griffstangen|Signalhalter|Gealtert|NEMSchacht|KKKinematik||Radsatzhersteller|Innenmaß|Spurkranzhöhe|||||||||||DecoderAdresse||||||Verwaltungszeichen||Waggonzeichnung|||||||||||||",
    "xwacaintern||||WagonNumber||Company||ClassificationII||ClassificationIII||ClassificationIV|||UIC||Description||Brake||Speed||Wheelweight||WheelArrangement||Weight|SeatsI|SeatsII||Lengthoverbuffer||Wheelbase||Loadingcapacity||Loadinglength||Loadingarea||Loadingvolume||Loadingremarks|RIVPic||Line1|Line2|Line3|CyclePic||HomeStation||HomeDepot||Heater||Power||Remarks||Counter||OperationTime||Rollbockfähig||Modellbeschriftung||Modellmerkmale||Eigentümer||Federpuffer||Kupplung||Kupplungskopf||Radsätze||Hersteller||ModellLÜP||Modellgewicht||Merkmal Wagenboden||Revision|Griffstangen|Signalhalter|Gealtert|NEMSchacht|KKKinematik||Radsatzhersteller|Innenmaß|Spurkranzhöhe||||||||||||||||||||||||||||||||",
    "jmri||||locomotive.roadNumber||locomotive.roadName|||||||||||locomotive.comment||||locomotive.maxSpeed||||||||||||||||||||||||||||||||||||||||||||||||||locomotive.owner||||||||||locomotive.mfg||||||||||||||||||||||||||||locomotive.dccAddress|||||||||||||||||||||",
    "Anothaft||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||",
    "Gziegler||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||" 

]
data.forEach(res => {
    tabconvert.push(res.split("|"));
});
console.log(tabconvert);
}